export const restaurants = [
  {
    id: "rest-1",
    name: "Taste of Italy",
    image: "/images/restaurants/pizza-restaurant-1.jpg",
    cuisine: ["Italian", "Pizza"],
    rating: 4.8,
    deliveryTime: "25-35 min",
    deliveryFee: "$2.99",
    minOrder: "$10.00",
  },
  {
    id: "rest-2",
    name: "XBurgers Outlet",
    image: "/images/restaurants/burger-restaurant-1.jpg",
    cuisine: ["American", "Burgers"],
    rating: 4.6,
    deliveryTime: "20-30 min",
    deliveryFee: "$1.99",
    minOrder: "$12.00",
  },
  {
    id: "rest-3",
    name: "Dosa Palace",
    image: "/images/restaurants/sushi-restaurant-1.jpg",
    cuisine: ["Japanese", "Sushi"],
    rating: 4.9,
    deliveryTime: "30-40 min",
    deliveryFee: "$3.99",
    minOrder: "$15.00",
  },
  {
    id: "rest-4",
    name: "TJ's",
    image: "/images/restaurants/taco-restaurant-1.jpg",
    cuisine: ["Mexican", "Tacos"],
    rating: 4.5,
    deliveryTime: "20-30 min",
    deliveryFee: "$2.49",
    minOrder: "$10.00",
  },
  {
    id: "rest-5",
    name: "Crunchy Bite",
    image: "/images/restaurants/pasta-restaurant-1.jpg",
    cuisine: ["Italian", "Pasta"],
    rating: 4.7,
    deliveryTime: "25-35 min",
    deliveryFee: "$2.99",
    minOrder: "$12.00",
  },
  {
    id: "rest-6",
    name: "Corner Cafe",
    image: "/images/restaurants/indian-restaurant-1.jpg",
    cuisine: ["Indian", "Curry"],
    rating: 4.6,
    deliveryTime: "30-40 min",
    deliveryFee: "$3.49",
    minOrder: "$15.00",
  },
  {
    id: "rest-7",
    name: "Creative Foods",
    image: "/images/restaurants/chinese-restaurant-1.jpg",
    cuisine: ["Chinese", "Noodles"],
    rating: 4.4,
    deliveryTime: "25-35 min",
    deliveryFee: "$2.99",
    minOrder: "$12.00",
  },
  {
    id: "rest-8",
    name: "Vikas Confectionary",
    image: "/images/restaurants/salad-restaurant-1.jpg",
    cuisine: ["Healthy", "Salads"],
    rating: 4.5,
    deliveryTime: "15-25 min",
    deliveryFee: "$1.99",
    minOrder: "$10.00",
  },
]

export const menuItems = [
  {
    id: "item-1",
    restaurantId: "rest-1",
    name: "Margherita Pizza",
    description: "Classic pizza with tomato sauce, mozzarella, and basil",
    price: 12.99,
    image: "/images/food/pizza-1.jpg",
    category: "Pizza",
  },
  {
    id: "item-2",
    restaurantId: "rest-1",
    name: "Pepperoni Pizza",
    description: "Pizza with tomato sauce, mozzarella, and pepperoni",
    price: 14.99,
    image: "/images/food/pizza-2.jpg",
    category: "Pizza",
  },
  {
    id: "item-3",
    restaurantId: "rest-1",
    name: "Garlic Bread",
    description: "Freshly baked bread with garlic butter",
    price: 4.99,
    image: "/images/food/bread-1.jpg",
    category: "Sides",
  },
  {
    id: "item-4",
    restaurantId: "rest-1",
    name: "Caesar Salad",
    description: "Fresh romaine lettuce with Caesar dressing and croutons",
    price: 7.99,
    image: "/images/food/salad-1.jpg",
    category: "Salads",
  },
  {
    id: "item-5",
    restaurantId: "rest-1",
    name: "Tiramisu",
    description: "Classic Italian dessert with coffee and mascarpone",
    price: 6.99,
    image: "/images/food/dessert-1.jpg",
    category: "Desserts",
  },
  {
    id: "item-6",
    restaurantId: "rest-2",
    name: "Classic Burger",
    description: "Beef patty with lettuce, tomato, and special sauce",
    price: 9.99,
    image: "/images/food/burger-1.jpg",
    category: "Burgers",
  },
  {
    id: "item-7",
    restaurantId: "rest-2",
    name: "Cheeseburger",
    description: "Beef patty with cheese, lettuce, tomato, and special sauce",
    price: 10.99,
    image: "/images/food/burger-2.jpg",
    category: "Burgers",
  },
  {
    id: "item-8",
    restaurantId: "rest-2",
    name: "Bacon Burger",
    description: "Beef patty with bacon, cheese, lettuce, and special sauce",
    price: 12.99,
    image: "/images/food/burger-3.jpg",
    category: "Burgers",
  },
  {
    id: "item-9",
    restaurantId: "rest-2",
    name: "French Fries",
    description: "Crispy golden fries with sea salt",
    price: 3.99,
    image: "/images/food/fries-1.jpg",
    category: "Sides",
  },
  {
    id: "item-10",
    restaurantId: "rest-2",
    name: "Milkshake",
    description: "Creamy milkshake with your choice of flavor",
    price: 4.99,
    image: "/images/food/drink-1.jpg",
    category: "Drinks",
  },
  {
    id: "item-11",
    restaurantId: "rest-3",
    name: "California Roll",
    description: "Crab, avocado, and cucumber roll",
    price: 8.99,
    image: "/images/food/sushi-1.jpg",
    category: "Rolls",
  },
  {
    id: "item-12",
    restaurantId: "rest-3",
    name: "Salmon Nigiri",
    description: "Fresh salmon over pressed vinegared rice",
    price: 6.99,
    image: "/images/food/sushi-2.jpg",
    category: "Nigiri",
  },
  {
    id: "item-13",
    restaurantId: "rest-3",
    name: "Spicy Tuna Roll",
    description: "Spicy tuna and cucumber roll",
    price: 9.99,
    image: "/images/food/sushi-3.jpg",
    category: "Rolls",
  },
  {
    id: "item-14",
    restaurantId: "rest-3",
    name: "Miso Soup",
    description: "Traditional Japanese soup with tofu and seaweed",
    price: 3.99,
    image: "/images/food/soup-1.jpg",
    category: "Soups",
  },
  {
    id: "item-15",
    restaurantId: "rest-3",
    name: "Edamame",
    description: "Steamed soybean pods with sea salt",
    price: 4.99,
    image: "/images/food/sides-1.jpg",
    category: "Sides",
  },
  // Additional menu items for rest-4 (Taco Time)
  {
    id: "item-16",
    restaurantId: "rest-4",
    name: "Beef Taco",
    description: "Seasoned ground beef with lettuce, cheese, and salsa in a corn tortilla",
    price: 3.99,
    image: "/images/food/taco-1.jpg",
    category: "Tacos",
  },
  {
    id: "item-17",
    restaurantId: "rest-4",
    name: "Chicken Quesadilla",
    description: "Grilled chicken with melted cheese in a flour tortilla",
    price: 8.99,
    image: "/images/food/quesadilla-1.jpg",
    category: "Quesadillas",
  },
  {
    id: "item-18",
    restaurantId: "rest-4",
    name: "Beef Burrito",
    description: "Seasoned beef with rice, beans, cheese, and salsa wrapped in a flour tortilla",
    price: 9.99,
    image: "/images/food/burrito-1.jpg",
    category: "Burritos",
  },
  // Additional menu items for rest-5 (Pasta Palace)
  {
    id: "item-19",
    restaurantId: "rest-5",
    name: "Spaghetti Bolognese",
    description: "Spaghetti with rich meat sauce and parmesan cheese",
    price: 12.99,
    image: "/images/food/pasta-1.jpg",
    category: "Pasta",
  },
  {
    id: "item-20",
    restaurantId: "rest-5",
    name: "Fettuccine Alfredo",
    description: "Fettuccine pasta with creamy alfredo sauce",
    price: 13.99,
    image: "/images/food/pasta-2.jpg",
    category: "Pasta",
  },
  // Additional menu items for rest-6 (Curry Corner)
  {
    id: "item-21",
    restaurantId: "rest-6",
    name: "Butter Chicken",
    description: "Tender chicken in a rich, creamy tomato sauce",
    price: 14.99,
    image: "/images/food/curry-1.jpg",
    category: "Curry",
  },
  {
    id: "item-22",
    restaurantId: "rest-6",
    name: "Paneer Tikka Masala",
    description: "Cottage cheese cubes in a spiced tomato gravy",
    price: 13.99,
    image: "/images/food/paneer-1.jpg",
    category: "Curry",
  },
  {
    id: "item-23",
    restaurantId: "rest-6",
    name: "Chicken Biryani",
    description: "Fragrant basmati rice cooked with chicken and aromatic spices",
    price: 15.99,
    image: "/images/food/biryani-1.jpg",
    category: "Biryani",
  },
  // Additional menu items for rest-7 (Noodle Nirvana)
  {
    id: "item-24",
    restaurantId: "rest-7",
    name: "Vegetable Chow Mein",
    description: "Stir-fried noodles with mixed vegetables",
    price: 10.99,
    image: "/images/food/noodles-1.jpg",
    category: "Noodles",
  },
  {
    id: "item-25",
    restaurantId: "rest-7",
    name: "Kung Pao Chicken",
    description: "Spicy stir-fried chicken with peanuts and vegetables",
    price: 12.99,
    image: "/images/food/chinese-1.jpg",
    category: "Main Course",
  },
  // Additional menu items for rest-8 (Salad Sanctuary)
  {
    id: "item-26",
    restaurantId: "rest-8",
    name: "Greek Salad",
    description: "Fresh salad with tomatoes, cucumbers, olives, and feta cheese",
    price: 8.99,
    image: "/images/food/salad-1.jpg",
    category: "Salads",
  },
  {
    id: "item-27",
    restaurantId: "rest-8",
    name: "Quinoa Bowl",
    description: "Nutritious quinoa with roasted vegetables and tahini dressing",
    price: 10.99,
    image: "/images/food/salad-2.jpg",
    category: "Bowls",
  },
]
